### ISSUE TITLE
[Bug] Graphback Init command is not working with custom template

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1043]
`graphback init <name> --templateUrl` is not working.

### Steps to Reproduce

Install the latest version of Graphback

Run:

```sh
$ graphback init test --templateUrl=https://github.com/aerogear/modern-appdev-workshop

Create Graphback project from available templates

Positionals:
  name  Project name                                         [string] [required]

Options:
  --templateName  Name of the predefined template                       [string]
  --templateUrl   GitHub URL of the template. For example
                  (http://github.com/wtrocki/graphback-hapijs#master)   [string]
  -h, --help      Show help                                            [boolean]
  -v, --version   Show version number                                  [boolean]

CwdError: ENOENT: Cannot cd into '/home/ephelan/code/playground/test'
    at /home/ephelan/code/aerogear/graphback/packages/graphback-cli/node_modules/tar/lib/mkdir.js:100:17
    at FSReqCallback.oncomplete (fs.js:154:23) {
  path: '/home/ephelan/code/playground/test',
  code: 'ENOENT'
}
```

**Comment by wtrocki** [comment]
I think positional parameters need to be the last before named ones.
``` 
graphback init --templateUrl=https://github.com/aerogear/modern-appdev-workshop test ```

**Comment by craicoverflow** [comment]
> I think positional parameters need to be the last before named ones.
> 
> ```
> graphback init --templateUrl=https://github.com/aerogear/modern-appdev-workshop test 
> ```

This gives the same error result.
