### ISSUE TITLE
Cannot create a user record with only an id

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1088]
Here is my model:

```graphql
"""
@model
"""
type User {
  id: ID!
}
```

And here's the generated schema:

```graphql
## NOTE: This schema was generated by Graphback and should not be changed manually

type Mutation {
  createUser(input: UserInput): User!
  updateUser(input: UserInput): User!
}

type Query {
  findAllUsers(limit: Int, offset: Int): [User]!
  findUsers(fields: UserInput, limit: Int, offset: Int): [User]!
}

"""@model"""
type User {
  id: ID!
}

input UserInput {
  id: ID
}
```

I would expect to be able to execute a mutation like this:

```graphql
mutation {
  createUser {
    id
  }
}
```

But when I do, I get:

```json
{
  "errors": [
    {
      "message": "No result from database: Cannot create user",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: No result from database: Cannot create user",
            "    at PgKnexDBDataProvider.<anonymous> (/home/lastmjs/development/single-shuffle/node_modules/@graphback/runtime-knex/src/PgKnexDBDataProvider.ts:28:15)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/home/lastmjs/development/single-shuffle/node_modules/tslib/tslib.js:104:62)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

There seems to be something wrong with default values, perhaps the postgres SQL query for having no values, which needs to be something like `insert into public.user values(default);`, is not being constructed correctly.

**Comment by craicoverflow** [comment]
Hey @lastmjs! Yeah, that's a bug! Thanks for letting us know. I've a fix up in https://github.com/aerogear/graphback/pull/1106 - we will get it released ASAP.

**Comment by craicoverflow** [comment]
```gql
createNote(input: NoteInput): Note
```

Graphback's resolvers pass `args.input` to the database, which is used to create the item.

```gql
mutation {
  createUser {
    id
  }
}
```

By using the mutation this way, `input` is undefined. If you want to create a user without supplying data you can do:

```gql
mutation createUser {
  createUser(input: {}) {
    id
  }
}
```

This creates an empty object which will successfully create a user

**Comment by wtrocki** [comment]
@craicoverflow Let's make input required then

**Comment by craicoverflow** [comment]
Input is required, Closing.
