### ISSUE TITLE
Error: ThunkComposer() returns empty value: undefined with Graphback Alpa release 0.14.0-dev2

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1299]
Starting a server with this model file https://github.com/aerogear/OpenVolunteerPlatform/blob/chore/update-graphback/platform/model/main.graphql and graphback v0.14.0-dev2 I am getting an error below
```
Error: ThunkComposer() returns empty value: undefined
    at ThunkComposer.get ofType [as ofType] (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/ThunkComposer.js:24:13)
    at getTypeNode (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:250:28)
    at /Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:323:18
    at Array.map (<anonymous>)
    at getInputValueDefinitionNodes (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:321:21)
    at getInputObjectTypeDefinitionNode (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/definitionNode.js:55:13)
    at InputTypeComposer.getType (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/InputTypeComposer.js:412:81)
    at NonNullComposer.getType (/Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/NonNullComposer.js:27:52)
    at /Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/ObjectTypeComposer.js:322:23
    at /Users/machi/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/graphql-compose/lib/utils/misc.js:134:19
```

The error is reproducible using this OVP's branch https://github.com/aerogear/OpenVolunteerPlatform/tree/chore/update-graphback

**Comment by wtrocki** [comment]
That is issue with generating some specific input type for the object. We need to selectively remove objects from schema to see what is failing.

Generally if could be one of the relationships we have there

**Comment by machi1990** [comment]
Yeap. 

I planned to dig deeper today with a simple model below:

```
"""
@model
"""
type  Issue {
  id: ID!
  name: IssueType
}

enum IssueType {
 BUG
 QUESTION
 FEATURE_REQUEST
}
```

1. From my understand the issue came here https://github.com/aerogear/graphback/blob/master/packages/graphback-core/src/crud/mappingHelpers.ts#L159 since we do not check for enum values thus returning `undefined` always for enum types.

2. Also judging from https://github.com/aerogear/graphback/blob/master/packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts#L148 it seems like the Filter input types lacks support for enum types, which I think it is something we'll like to do. This logic is not always the case e.g here https://github.com/aerogear/graphback/blob/master/packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts#L178 where the outstanding type of an enum field is `undefined` as observed in (1) above.

**Comment by wtrocki** [comment]
@machi1990 world class job. If you already done some investigation maybe you want to fix this with some help from team?

I think we should have quick win if we map enums to strings as we do with other scalars.

**Comment by machi1990** [comment]
@wtrocki great. I have opened #1306.
