### ISSUE TITLE
Broken template in 0.14.0-alpha2

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1362]
**Graphback Version**: 0.14.0-alpha2

I created a new application using the latest alpha release of Graphback. However the template appears to be using the runtime API brought in by https://github.com/aerogear/graphback/pull/1219, which never made it to master.

```sh
❯ yarn develop
yarn run v1.22.4
$ ts-node src/index.ts

/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:423
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/runtime.ts:1:10 - error TS2305: Module '"../node_modules/graphback/types"' has no exported member 'graphback'.

1 import { graphback } from 'graphback'
           ~~~~~~~~~

    at createTSError (/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:423:12)
    at reportTSError (/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:427:19)
    at getOutput (/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:554:36)
    at Object.compile (/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:760:32)
    at Module.m._compile (/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:839:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ephelan/code/playground/test-0.14/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by craicoverflow** [comment]
This is probably just a matter of updating the templates branch.

**Comment by wtrocki** [comment]
https://github.com/aerogear/graphback/tree/templates-0.14.0
