### ISSUE TITLE
`graphback init` throws an error when creating fullstack templates

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1483]
### Steps to reproduce

```
❯ npx graphback-cli@0.14.0-alpha4 init fullstack-issue
```

Choose one of the fullstack templates, for example `apollo-fullstack-react-postgres-ts`.

The following error is thrown:

```
Error: EEXIST: file already exists, mkdir '/home/ephelan/code/playground/fullstack-issue/client'
    at Object.mkdirSync (fs.js:840:3)
    at Object.<anonymous> (/home/ephelan/.npm/_npx/49060/lib/node_modules/graphback-cli/dist/init/starterTemplates.js:135:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ephelan/.npm/_npx/49060/lib/node_modules/graphback-cli/node_modules/tslib/tslib.js:110:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/home/ephelan/code/playground/fullstack-issue/client'
}
```

Looks like the backend templates already have a client subfolder so it can't create a new one.

**Comment by craicoverflow** [comment]
Creating the backend template creates a `client` symlink:

```
client -> ../ts-react-apollo-client
```

**Comment by wtrocki** [comment]
Our init command takes client and trie to compose them. If you have already client app in the folder after seeing this error message then we can possibly rely on symlink when exporting data and ignore composition.

**Comment by craicoverflow** [comment]
> I think we should force override symlink when creating template using init.

Agreed.
