### ISSUE TITLE
[Discussion] SchemaPlugin is always default, when a user adds a custom one (with different configs) it does not play very well together

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1584]
1. From this line https://github.com/aerogear/graphback/blob/master/packages/graphback/src/buildGraphbackAPI.ts#L82 we require the schema plugin to be the default but a user may add it so that the schema is generated in a custom file like what is done in https://github.com/aerogear/graphback/blob/master/integration/tests/runtime-workflow-postgres.ts#L48-L50. 

But from this PR https://github.com/aerogear/graphback/pull/1574 with have seen it causing issues like 
```
    Error: Non-model NoteResultList.items maps to Graphback model (Note) which is not allowed.
        at /home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts:296:15
        at Array.map (<anonymous>)
        at mapObjectInputFields (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts:289:17)
        at Object.addCreateObjectInputType (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts:319:13)
        at /home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts:731:11
        at Map.forEach (<anonymous>)
        at SchemaComposer.forEach (/home/manyanda/Documents/Projects/aerogear/graphback/node_modules/graphql-compose/lib/TypeStorage.js:37:23)
        at SchemaCRUDPlugin.createSchemaCRUDTypes (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts:724:20)
        at SchemaCRUDPlugin.buildSchemaForModels (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts:135:10)
        at SchemaCRUDPlugin.transformSchema (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts:63:10)
        at GraphbackPluginEngine.createSchema (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-core/src/plugin/GraphbackPluginEngine.ts:66:32)
        at GraphbackPluginEngine.createResources (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback-core/src/plugin/GraphbackPluginEngine.ts:50:10)
        at Object.buildGraphbackAPI (/home/manyanda/Documents/Projects/aerogear/graphback/packages/graphback/src/buildGraphbackAPI.ts:92:33)
        at /home/manyanda/Documents/Projects/aerogear/graphback/integration/tests/runtime-workflow-mongo.ts:42:20
        at Generator.next (<anonymous>)
        at fulfilled (/home/manyanda/Documents/Projects/aerogear/graphback/node_modules/tslib/tslib.js:112:62)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

      at tests/runtime-workflow-mongo.ts:59:13

```

The error occurs since we attempt to do a tranformation of something which was generated from the defaullt plugin (the first iteration.)
  
Opening issue to see how we approach cases where a user supply a custom instance of the schema plugin.

2. A user might as well pass a multiple instance of the same plugin. 

https://github.com/aerogear/graphback/blob/master/packages/graphback/src/buildGraphbackAPI.ts#L83

From the line above, we have user supplied `plugins`, this can contain duplicates. Do we allow this configuration?  

/cc @craicoverflow @wtrocki

**Comment by wtrocki** [comment]
I think we can action this by utilizing plugin name. If you want to override schema plugin or pass it directly it needs to be the same name. We can also ensure that we always have the same name. 

When we do all problems should disappear (considering we document that schema plugin can be extended but name should not be changed)

**Comment by machi1990** [comment]
> I think we can action this by utilizing plugin name. If you want to override schema plugin or pass it directly it needs to be the same name. We can also ensure that we always have the same name.
> 
> When we do all problems should disappear (considering we document that schema plugin can be extended but name should not be changed)

Yes, in doing so we should always prefer the user supplied one if any while defaulting to `new SchemaPlugin()`.
This ofcourse has to come first before any other plugins.

**Comment by wtrocki** [comment]
Yep. This makes sense so I would go for it!
