### ISSUE TITLE
Using CrudService throws an error in custom resolvers when Setting selectedFields throws an error once subscriptions are defined 

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1813]
Encountered this error when testing out 0.16.0-aplha1 in OVP, but I believe this to be an existing bug since 0.15, because of  https://github.com/aerogear/graphback/pull/1748/files#diff-92c6b98f36b0706670c511ec84acc609R60

```ts
error: TypeError: Cannot set property 'selectedFields' of undefined
      at CRUDService.<anonymous> (/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/@graphback/datasync/node_modules/@graphback/core/src/runtime/CRUDService.ts:60:47)
      at Generator.next (<anonymous>)
      at /Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/tslib/tslib.js:115:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/tslib/tslib.js:111:16)
      at CRUDService.update (/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/@graphback/datasync/node_modules/@graphback/core/dist/runtime/CRUDService.js:38:24)
      at AMQCRUDService.update (/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/@graphback/core/src/runtime/GraphbackProxyService.ts:24:32)
      at AMQCRUDService.update (/Projects/aerogear/OpenVolunteerPlatform/platform/node_modules/@graphback/keycloak-authz/src/KeycloakCrudService.ts:60:18)
```

I'll provide a fix.

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers
