### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1860]
This query fails:

```graphql
query {
  findCalls(filter: {
    id: {
      eq: 150
    }
  }) {
    items {
      id
      company {
        id
        name
        users {
          user {
            email
            is_active
          }
        }
      }
    }
  }
}
```
Here is the result:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'toString' of undefined",
      "locations": [
        {
          "line": 9,
          "column": 11
        }
      ],
      "path": [
        "findCalls",
        "items",
        0,
        "company",
        "users",
        0,
        "user"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'toString' of undefined",
            "    at /var/task/node_modules/@graphback/codegen-schema/dist/SchemaCRUDPlugin.js:599:88",
            "    at Array.find (<anonymous>)",
            "    at /var/task/node_modules/@graphback/codegen-schema/dist/SchemaCRUDPlugin.js:599:46",
            "    at Array.map (<anonymous>)",
            "    at SchemaCRUDPlugin.<anonymous> (/var/task/node_modules/@graphback/codegen-schema/dist/SchemaCRUDPlugin.js:598:33)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/var/task/node_modules/tslib/tslib.js:112:62)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "findCalls": {
      "items": [
        {
          "id": "150",
          "company": null
        }
      ]
    }
  }
}
```
When I add `id` to the selection set of users.user, the query succeeds:

```graphql
query {
  findCalls(filter: {
    id: {
      eq: 150
    }
  }) {
    items {
      id
      company {
        id
        name
        users {
          user {
            id
            email
            is_active
          }
        }
      }
    }
  }
}
```
Companies and users have a many-to-many relationship, so there is a join table called Companies_users that looks like this:

```graphql
type Companies_users {
    id: ID! # Note that this id exists in the schema because it is necessary, but my database actually does not have this field. Not usre if that matters in this case
    company: Companies!
    user: Users!
}
```

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by machi1990** [comment]
This looks like it is related to https://github.com/aerogear/graphback/issues/1752 and the more global one about  better support for many to many relationships.

**Comment by machi1990** [comment]
> This looks like it is related to #1752?

This only happens in 0.16.0-alpha3 after https://github.com/aerogear/graphback/pull/1834.  #1861 should fix this issue!

**Comment by machi1990** [comment]
@lastmjs we dropped [0.16.0-alpha4](https://github.com/aerogear/graphback/releases/tag/0.16.0-alpha4) to take care of this issue. Mind checking and see it fixes the issue for your. Feel free to re-open if it's not the case.

**Comment by lastmjs** [comment]
It works! Thanks a ton

**Comment by machi1990** [comment]
Thanks for reporting back!
