### ISSUE TITLE
Cannot return null for non-nullable field Users.email.

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1876]
This is a strange one. Here is my query:

```graphql
        query ($callId: ID!) {
            getCalls(id: $callId) {
                duration_events {
                    user {
                        id
                    }
                }
                company {
                    users {
                        user {
                            email
                        }
                    }
                }
            }
        }
```
Executing this query, I get the following result:

```graphql
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Users.email.",
      "locations": [
        {
          "line": 11,
          "column": 11
        }
      ],
      "path": [
        "getCalls",
        "company",
        "users",
        0,
        "user",
        "email"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Users.email.",
            "    at completeValue (/var/task/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/var/task/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/var/task/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/var/task/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/var/task/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/var/task/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/var/task/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValue (/var/task/node_modules/graphql/execution/execute.js:557:21)",
            "    at /var/task/node_modules/graphql/execution/execute.js:492:16",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "getCalls": {
      "duration_events": [
        {
          "user": {
            "id": "21"
          }
        },
        {
          "user": {
            "id": "21"
          }
        },
        {
          "user": {
            "id": "21"
          }
        }
      ],
      "company": null
    }
  }
}
```
Now, when I add the `email` field to the user selected in `duration_events`, the query works as expected. Here is the query that works:

```graphql
        query ($callId: ID!) {
            getCalls(id: $callId) {
                duration_events {
                    user {
                        id
                      	email # adding this makes the query work
                    }
                }
                company {
                    users {
                        user {
                            email
                        }
                    }
                }
            }
        }
```
Not sure why this is happening

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by wtrocki** [comment]
This looks like generic GraphQL situation. We return User object that has required field email. 
If returned object is missing email graphql validation will fail.

https://spectrum.chat/graphql/general/cannot-return-null-for-non-nullable-field-in-graphql~7fe90e5f-2895-457f-a7b9-e2839491f5fc?authed=true

This looks like issue with your own queries/schema

**Comment by lastmjs** [comment]
I'm not sure what you mean? I should be able to omit the email field in the selection set, not sure why that would cause this error. If I only select the id of a user in the selection set, that should work just as well as providing the email in the selection set.
