### ISSUE TITLE
createIndexesTest is unstable

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1936]
I've seen the test failing in separate random occasions and had to re-start CI to make it pass. 

The failure is: 
```
FAIL  packages/graphback-runtime-mongodb/tests/createIndexesTest.ts
  ● MongoDB indexing › can create relation indexes

    MongoError: ns does not exist: test.comment

      at MessageStream.messageHandler (node_modules/mongodb/lib/cmap/connection.js:266:20)
      at processIncomingData (node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (node_modules/mongodb/lib/cmap/message_stream.js:42:5)
```

See https://app.circleci.com/pipelines/github/aerogear/graphback/7359/workflows/259093cd-6792-4e23-bb39-b7632159eb02/jobs/7506 for example

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers
