### ISSUE TITLE
[30min] Graphback empty schema do not provide clear error message

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#302]
We do not check or provide any information when there is no model. 
To replicate:

```
? Choose a template to bootstrap apollo-starter-ts
? Do you want to include a example model? No
? Choose your database PostgreSQL
? Do you want to generate client-side queries? Yes
```
then execute generate and npm run develop.

```
GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/Users/wtrocki/Projects/live-demos/interface-tests/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/wtrocki/Projects/live-demos/interface-tests/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/Users/wtrocki/Projects/live-demos/interface-tests/node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/Users/wtrocki/Projects/live-demos/interface-tests/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/wtrocki/Projects/live-demos/interface-tests/node_modules/graphql/language/parser.js:111:25)
    at parse (/Users/wtrocki
```

**Comment by wtrocki** [comment]
Cli is going to be deprecated now.
