### ISSUE TITLE
Graphback fails to initialize

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#431]
{ Error: ENOENT: no such file or directory, open '/test-gr/model/Note.graphql'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at Object.addModel (/Users/wtrocki/.nvm/versions/node/v10.15.3/lib/node_modules/graphback-cli/dist/templates/modelTemplates.js:38:10)
    at Object.<anonymous> (/Users/wtrocki/.nvm/versions/node/v10.15.3/lib/node_modules/graphback-cli/dist/helpers/init.js:141:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/wtrocki/.nvm/versions/node/v10.15.3/lib/node_modules/graphback-cli/node_modules/tslib/tslib.js:107:62)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/wtrocki/Projects/sandbox/test-gr/model/Note.graphql' }

**Comment by wtrocki** [comment]
Fixed in 0.9.5
