### ISSUE TITLE
UnhandledPromiseRejectionWarning: error: syntax error at or near "primary"

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#831]
I am getting the following error when I run the runtime example twice with database migrations on.

```
(node:91221) UnhandledPromiseRejectionWarning: error: syntax error at or near "primary"
    at Connection.parseE (/home/ephelan/code/aerogear/graphback/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/ephelan/code/aerogear/graphback/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/ephelan/code/aerogear/graphback/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:91221) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:91221) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:91221) UnhandledPromiseRejectionWarning: error: syntax error at or near "primary"
    at Connection.parseE (/home/ephelan/code/aerogear/graphback/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/ephelan/code/aerogear/graphback/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/ephelan/code/aerogear/graphback/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
warning.js:32
```

It creates the database the first time, but running it again fails with above error.

**Comment by craicoverflow** [comment]
Issue is also present in CLI:

```
alter table "public"."note" alter column "ownerId" type serial primary key using ("ownerId"::serial primary key) - syntax error at or near "primary"
```

**Comment by craicoverflow** [comment]
> ```
> alter table "public"."note" alter column "ownerId" type serial primary key using ("ownerId"::serial primary key) - syntax error at or near "primary"
> ```

After investigation it looks like the following is happening:

The ownerId foreign key field is being given the SERIAL data type when `graphql-migrations` geneerates an abstract database.

Note.ownerID maps to User.id (type ID), and ID is mapped to serial in database.

We shoule ensure that SERIAL is only used for primary keys, and map ID to Int otherwise.
